# Generated by Django 5.1.3 on 2024-12-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("environmental_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Region",
            new_name="Country",
        ),
        migrations.RenameField(
            model_name="historicalenvironmentalrecord",
            old_name="region",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="realtimeenvironmentalrecord",
            old_name="region",
            new_name="country",
        ),
    ]
